Test Project: Vector< T > Class Template Reference
Vector< T > Class Template Reference
Classes
class Iterator
Public Member Functions
Vector ()
Constructs an empty container, with no elements.
Vector (const unsigned int size=5, const T value=0)
Constructs a container with size elements.
Vector (const Vector &copy)
~Vector ()
Vector< T > & operator= (const Vector< T > &value)
T & operator[] (const int n) const
T & operator* () const
unsigned int size () const
unsigned int capacity () const
bool empty ()
check vector is empty?
void push_back (const T value)
void pop_back ()
delete last element and decrement vector size
void resize (const unsigned int size, const T value=0)
void reserve (const unsigned int size)
void shrink_to_fit ()
Iterator begin () const
Iterator end () const
Iterator rbegin () const
Iterator rend () const
Detailed Description
template<typename T>
class Vector< T >
Definition at line 5 of file vector.cpp.
Constructor & Destructor Documentation
Vector() [1/3]
template<typename T> Vector< T >::Vector () inline
Constructs an empty container, with no elements.
Definition at line 16 of file vector.cpp.
                 {
             mSize = 0;
             mCapacity = 0;
             vector = new T [mSize];
         }
Vector() [2/3]
template<typename T> Vector< T >::Vector (const unsigned int size = 5, const T value = 0) inline
Constructs a container with size elements.
Each element is a copy of value.
Parameters
size - number of elements
value - value for each element
Definition at line 29 of file vector.cpp.
References Vector< T >::size().
{
             try
             {
                 this->mSize = size;
                 this->mCapacity = size;
                 this->vector = new T[size];
                 for (int i = 0; i < size; ++i) {
                     this->vector[i] = value;
                 }
             }
             catch(const std::exception& e)
             {
                 std::cerr << e.what() <<" uncorected index" << '\n';
             }
         }
Vector() [3/3]
template<typename T> Vector< T >::Vector (const Vector< T > & copy) inline
Definition at line 48 of file vector.cpp.
{
             this->mSize = copy.mSize;
             this->mCapacity = copy.mCapacity;
             this->vector = new T[copy.mSize];
             for (int i = 0; i < mSize; ++i) {
                 this->vector[i] = copy.vector[i];
             }
         }
~Vector()
template<typename T> Vector< T >::~Vector () inline
Definition at line 58 of file vector.cpp.
                  {
             delete[] vector;
         }
Member Function Documentation
begin()
template<typename T> Iterator Vector< T >::begin () const inline
Definition at line 224 of file vector.cpp.
References Vector< T >::Iterator::Iterator().
Referenced by main().
{
             return Iterator(vector);
         }
capacity()
template<typename T> unsigned int Vector< T >::capacity () const inline
Definition at line 86 of file vector.cpp.
Referenced by main().
{
             return mCapacity;
         }
empty()
template<typename T> bool Vector< T >::empty () inline
check vector is empty?
Returns
return true when vector size = 0, else false
Definition at line 95 of file vector.cpp.
Referenced by main().
                      {
             return mSize == 0 ? true : false;
         }
end()
template<typename T> Iterator Vector< T >::end () const inline
Definition at line 229 of file vector.cpp.
References Vector< T >::Iterator::Iterator().
Referenced by main().
{
             return Iterator(vector + mSize);
         }
operator*()
template<typename T> T& Vector< T >::operator* () const inline
Definition at line 76 of file vector.cpp.
{
             return *vector;
         }
operator=()
template<typename T> Vector<T>& Vector< T >::operator= (const Vector< T > & value) inline
Definition at line 64 of file vector.cpp.
{
             this->mSize = value.mSize;
             this->mCapacity = value.mSize;
             this->vector = value.vector;
             return *this;
         }
operator[]()
template<typename T> T& Vector< T >::operator[] (const int n) const inline
Definition at line 72 of file vector.cpp.
{
             return *(vector + n);
         }
pop_back()
template<typename T> void Vector< T >::pop_back () inline
delete last element and decrement vector size
Definition at line 121 of file vector.cpp.
Referenced by main().
{
             mSize = mSize - 1;
         }
push_back()
template<typename T> void Vector< T >::push_back (const T value) inline
Definition at line 100 of file vector.cpp.
Referenced by main().
{
             if(mSize == mCapacity) {
                 mCapacity *= 2;
                 T* tmp = new T [mCapacity];
                 for (int i = 0; i < mSize; ++i) {
                     tmp[i] = vector[i];
                 }
                 tmp[mSize] = value;
                 delete[] vector;
                 vector = tmp;
             } else {
                 vector[mSize ] = value;
             }
             ++mSize;
         }
rbegin()
template<typename T> Iterator Vector< T >::rbegin () const inline
Definition at line 234 of file vector.cpp.
References Vector< T >::Iterator::Iterator().
Referenced by main().
{
             return Iterator(vector + mSize -1);
         }
rend()
template<typename T> Iterator Vector< T >::rend () const inline
Definition at line 239 of file vector.cpp.
References Vector< T >::Iterator::Iterator().
Referenced by main().
{
             return Iterator(vector - 1);
         }
reserve()
template<typename T> void Vector< T >::reserve (const unsigned int size) inline
Definition at line 159 of file vector.cpp.
References Vector< T >::size().
Referenced by main().
{
             if(mCapacity < size) {
                 mCapacity = size;
             }
         }
resize()
template<typename T> void Vector< T >::resize (const unsigned int size, const T value = 0) inline
Definition at line 126 of file vector.cpp.
References Vector< T >::size().
Referenced by main().
{
             T* tmp;
             if(mSize > size) {
                 mSize = size;
                 tmp = new T [mCapacity];
                 for(unsigned int i = 0; i < mSize; ++i) {
                     tmp[i] = vector[i];
                 }
                 delete[] vector;
                 vector = tmp;
             } else if(mSize < size && size > mCapacity){
                 tmp = new T [size];
                 for(unsigned int i = 0; i < mSize; ++i) {
                     tmp[i] = vector[i];
                 }
                 for(unsigned int i = mSize; i < size; ++i) {
                     tmp[i] = value;
                 }
                 mSize = mCapacity = size;
                 delete[] vector;
                 vector = tmp;
             } else if(mSize < size && size < mCapacity) {
                 for(unsigned int i = mSize; i < size; ++i) {
                     vector[i] = value;
                 }
                 mSize = size;
             }
         }
shrink_to_fit()
template<typename T> void Vector< T >::shrink_to_fit () inline
Definition at line 166 of file vector.cpp.
Referenced by main().
{
             mCapacity = mSize;
         }
size()
template<typename T> unsigned int Vector< T >::size () const inline
Definition at line 81 of file vector.cpp.
Referenced by main(), Vector< T >::reserve(), Vector< T >::resize(), and Vector< T >::Vector().
{
             return mSize;
         }
The documentation for this class was generated from the following file:
Vector/vector.cpp