Test Project: Vector::Iterator::Iterator
Iterator() [2/2]
template<typename T> Vector< T >::Iterator::Iterator () inline
Definition at line 175 of file vector.cpp.
Referenced by Vector< T >::begin(), Vector< T >::end(), Vector< T >::rbegin(), and Vector< T >::rend().
 : array(nullptr) {}