Test Project: List< T > Class Template Reference
List< T > Class Template Reference
Lists are sequence containers that allow non-contiguous memory allocation.
Classes
class Iterator
Public Member Functions
List ()
List (unsigned int size=0, int value=0)
void Valodik (int norParametr)
This function generate new data for Valodik.
List (const List &copy)
List & operator= (const List &obj)
~List ()
void push_back (const T &value)
It takes the element to be added as a parameter and adds it to the list container.
void push_front (const T &value)
It takes the element to be added as a parameter and adds it to the first container.
void pop_front ()
void pop_back ()
unsigned int size () const
bool empty () const
void remove (const T &value)
void insert_at (int pos, const T &elem)
void print ()
Iterator begin () const
Iterator end () const
Iterator rbegin () const
Iterator rend () const
Detailed Description
template<typename T>
class List< T >
Lists are sequence containers that allow non-contiguous memory allocation.
As compared to vector, list has slow traversal, but once a position has been found, insertion and deletion are quick.
Definition at line 9 of file list.cpp.
Constructor & Destructor Documentation
List() [1/3]
template<typename T> List< T >::List () inline
Definition at line 23 of file list.cpp.
               {
             head = NULL;
             tail = NULL;
             mSize = 0;
             std::cout << "defolt" << std::endl;
         }
List() [2/3]
template<typename T> List< T >::List (unsigned int size = 0, int value = 0) inline
Definition at line 31 of file list.cpp.
References List< T >::size().
{
             mSize = size;
             head = NULL;
             tail = NULL;
             for(int i = 0; i < size; ++i) {
                 Node* tmp = new Node();
                 tmp->data = value;
                 tmp->prev = NULL;
                 tmp->next = head;
                 if(head != NULL) {
                     head->prev = tmp;
                 }
                 head = tmp;
                 if(i == 0) {
                     tail = tmp;
                 }
             }
         }
List() [3/3]
template<typename T> List< T >::List (const List< T > & copy) inline
Definition at line 63 of file list.cpp.
{
             this->head = NULL;
             this->tail = NULL;
             Node* cur = copy.tail;
             for (int i = 0; i < copy.mSize; ++i) {
                 Node* tmp = new Node();
                 tmp->data = cur->data;
                 tmp->prev = head;
                 tmp->next = head;
                 head = tmp;
                 cur = cur->prev;
                 if(i == 0) {
                     tail = tmp;
                 }
             }
         }
~List()
template<typename T> List< T >::~List () inline
Definition at line 104 of file list.cpp.
                 {
             delete tail;
             delete head;
         }
Member Function Documentation
begin()
template<typename T> Iterator List< T >::begin () const inline
Definition at line 329 of file list.cpp.
{
             return Iterator(head);
         }
empty()
template<typename T> bool List< T >::empty () const inline
Definition at line 187 of file list.cpp.
{
             return mSize == 0 ? true : false;
         }
end()
template<typename T> Iterator List< T >::end () const inline
Definition at line 334 of file list.cpp.
{
             return Iterator(tail->next);
         }
insert_at()
template<typename T> void List< T >::insert_at (int pos, const T & elem) inline
Definition at line 222 of file list.cpp.
References List< T >::size().
{
             Node* tmp = new Node(); //new node
             int cout = size(); //size of list items
             //checks which on the index need add new item
             if(pos == 0) {
                 //push front
                 tmp->data = elem;
                 tmp->prev = NULL;
                 tmp->next = head;
                 if(head != NULL) {
                     head->prev = tmp;
                 } else {
                     tail =  tmp;
                     tail->prev = NULL;
                     tail->next = NULL;
                 }
                 head = tmp;
             } else  if (pos < cout && pos > 0){
                 //in the middle
                 Node* prev = head;
                 tmp->data = elem;
                 int i ;
                 //find prevuse element
                 for( i = 0; i < pos - 1;++i){
                     prev = prev->next;
                 }
                 tmp->next = prev->next;
                 prev->next->prev = tmp;
                 tmp->prev = prev;
                 prev->next = tmp;
             }
             else if (pos > 0 && pos == cout) {
                 //push_back
                 Node* tmp = new Node();
                 Node* cur = head;
                 tmp->data = elem;
                 for(int i = 0; i<pos-1; ++i){
                     cur = cur->next;
                 }
                 cur->next = tmp;
                 tmp->next = NULL;
                 tmp->prev = cur;
                 tail = tmp;
                 tail->prev = cur;
                 tail->next = NULL;
             }
             mSize++;
         }
operator=()
template<typename T> List& List< T >::operator= (const List< T > & obj) inline
Definition at line 82 of file list.cpp.
{
             Node* tmp = head;
             head = NULL;
             tail = NULL;
             delete tmp;
             tmp = obj.tail;
             for(int i = 0; i < mSize; ++i) {
                 Node* newNode = new Node();
                 newNode->data = tmp->data;
                 newNode->prev = head;
                 newNode->next = head;
                 head = newNode;
                 tmp = tmp->prev;
                 if(i == 0) {
                     tail = newNode;
                 }
             }
             return *this;
         }
pop_back()
template<typename T> void List< T >::pop_back () inline
Definition at line 168 of file list.cpp.
Referenced by main(), and List< T >::remove().
{
             Node* tmp = tail;
             if(tail->prev != NULL) {
                 tmp->prev->next = NULL;
                 tail = tmp->prev;
             } else {
                 head = NULL; //tail = NULL;
             }
             delete tmp;
             mSize--;
         }
pop_front()
template<typename T> void List< T >::pop_front () inline
Definition at line 157 of file list.cpp.
Referenced by List< T >::remove().
{
             Node* tmp = head;
             if(tmp->next != NULL) {
             head = tmp->next;
             tmp->next->prev = NULL;
             }
             mSize--;
             delete tmp;
         }
print()
template<typename T> void List< T >::print () inline
Definition at line 274 of file list.cpp.
                     {
             Node* cur = head;
             while(cur != NULL) {
                 std::cout << cur->data <<std::endl;
                 cur = cur->next;
             }
         }
push_back()
template<typename T> void List< T >::push_back (const T & value) inline
It takes the element to be added as a parameter and adds it to the list container.
Parameters
value - value for new added node of list
Definition at line 114 of file list.cpp.
Referenced by main().
{
             Node* tmp = new Node();
             tmp->data = value;
             if(head == NULL) {
                 head == tmp;
                 tail == tmp;
                 tail->next = NULL;
                 tail->prev = NULL;
                 head->next = NULL;
                 head->prev = NULL;
             } else {
             Node* cur = tail;
             cur->next = tmp;
             tmp->next = NULL;
             tmp->prev = cur;
             tail = tmp;
             tail->prev = cur;
             tail->next = NULL;
             mSize++;
             }
         }
push_front()
template<typename T> void List< T >::push_front (const T & value) inline
It takes the element to be added as a parameter and adds it to the first container.
Parameters
value - value for new added node of list
Definition at line 144 of file list.cpp.
{
             Node* tmp = new Node();
             tmp->data = value;
             tmp->prev = NULL;
             tmp->next = head;
             if(head != NULL) {
                 head->prev = tmp;
             }
             head = tmp;
             mSize++;
         }
rbegin()
template<typename T> Iterator List< T >::rbegin () const inline
Definition at line 339 of file list.cpp.
{
             return Iterator(tail);
         }
remove()
template<typename T> void List< T >::remove (const T & value) inline
Definition at line 194 of file list.cpp.
References List< T >::pop_back(), List< T >::pop_front(), and List< T >::size().
{
             Node* cur = head;
             unsigned int size = mSize;
             for (int i = 0; i < size; ++i) {
                 if(cur->data == value) {
                     if(i == 0) {
                         pop_front();
                     }
                     else if(i == size - 1) {
                         pop_back();
                     }
                     else {
                         Node* tmp = cur;
                         if(cur->prev == NULL) {
                             head = cur->next;
                             cur->next->prev = NULL;
                         } else {
                             cur->next->prev = cur->prev;
                             cur->prev->next = cur->next;
                         }
                         delete tmp;
                         mSize--;
                     }
                 }
                 cur = cur->next;
             }
         }
rend()
template<typename T> Iterator List< T >::rend () const inline
Definition at line 344 of file list.cpp.
{
             return Iterator(head->prev);
         }
size()
template<typename T> unsigned int List< T >::size () const inline
Definition at line 182 of file list.cpp.
Referenced by List< T >::insert_at(), List< T >::List(), and List< T >::remove().
{
             return mSize;
         }
Valodik()
template<typename T> void List< T >::Valodik (int norParametr) inline
This function generate new data for Valodik.
Todo:
Parameters
norParametr - new parametr
Definition at line 58 of file list.cpp.
{
         }
The documentation for this class was generated from the following file:
List/list.cpp