Test Project: Vector::size
size()
template<typename T> unsigned int Vector< T >::size () const inline
Definition at line 81 of file vector.cpp.
Referenced by main(), Vector< T >::reserve(), Vector< T >::resize(), and Vector< T >::Vector().
{
             return mSize;
         }