Test Project: Vector< T >::Iterator Class Reference
Vector< T >::Iterator Class Reference
Public Member Functions
Iterator (T *newArray)
Iterator ()
~Iterator ()
bool operator!= (const Iterator &itr) const
bool operator== (const Iterator &itr) const
Iterator operator++ (int)
Iterator operator++ ()
Iterator operator-- (int)
Iterator operator-- ()
Iterator operator+ (int n)
Iterator operator- (int n)
T & operator* () const
Public Attributes
T * array
Detailed Description
template<typename T>
class Vector< T >::Iterator
Definition at line 170 of file vector.cpp.
Constructor & Destructor Documentation
Iterator() [1/2]
template<typename T> Vector< T >::Iterator::Iterator (T * newArray) inline
Definition at line 173 of file vector.cpp.
 : array(newArray) {}
Iterator() [2/2]
template<typename T> Vector< T >::Iterator::Iterator () inline
Definition at line 175 of file vector.cpp.
Referenced by Vector< T >::begin(), Vector< T >::end(), Vector< T >::rbegin(), and Vector< T >::rend().
 : array(nullptr) {}
~Iterator()
template<typename T> Vector< T >::Iterator::~Iterator () inline
Definition at line 177 of file vector.cpp.
 {}
Member Function Documentation
operator!=()
template<typename T> bool Vector< T >::Iterator::operator!= (const Iterator & itr) const inline
Definition at line 179 of file vector.cpp.
References Vector< T >::Iterator::array.
{
                     return array != itr.array;
                 }
operator*()
template<typename T> T& Vector< T >::Iterator::operator* () const inline
Definition at line 217 of file vector.cpp.
References Vector< T >::Iterator::array.
{
                     return *array;
                 }
operator+()
template<typename T> Iterator Vector< T >::Iterator::operator+ (int n) inline
Definition at line 209 of file vector.cpp.
{
                     return array + n;
                 }
operator++() [1/2]
template<typename T> Iterator Vector< T >::Iterator::operator++ (int) inline
Definition at line 187 of file vector.cpp.
References Vector< T >::Iterator::array.
{
                     T* tmp = array;
                     array = array + 1;
                     return tmp;
                 }
operator++() [2/2]
template<typename T> Iterator Vector< T >::Iterator::operator++ () inline
Definition at line 193 of file vector.cpp.
References Vector< T >::Iterator::array.
{
                     array = array + 1;
                     return array;
                 }
operator-()
template<typename T> Iterator Vector< T >::Iterator::operator- (int n) inline
Definition at line 213 of file vector.cpp.
{
                     return array - n;
                 }
operator--() [1/2]
template<typename T> Iterator Vector< T >::Iterator::operator-- (int) inline
Definition at line 198 of file vector.cpp.
References Vector< T >::Iterator::array.
{
                     T* tmp = array;
                     array = array - 1;
                     return tmp;
                 }
operator--() [2/2]
template<typename T> Iterator Vector< T >::Iterator::operator-- () inline
Definition at line 204 of file vector.cpp.
References Vector< T >::Iterator::array.
{
                     array = array - 1;
                     return array;
                 }
operator==()
template<typename T> bool Vector< T >::Iterator::operator== (const Iterator & itr) const inline
Definition at line 183 of file vector.cpp.
References Vector< T >::Iterator::array.
{
                     return array == itr.array;
                 }
Member Data Documentation
array
template<typename T> T* Vector< T >::Iterator::array
Definition at line 172 of file vector.cpp.
Referenced by Vector< T >::Iterator::operator!=(), Vector< T >::Iterator::operator*(), Vector< T >::Iterator::operator++(), Vector< T >::Iterator::operator--(), and Vector< T >::Iterator::operator==().
The documentation for this class was generated from the following file:
Vector/vector.cpp