Test Project: main
main()
int main ()
Definition at line 10 of file fibonachi.cpp.
References entering(), fibo(), and recFibo().
            {
     int size;
     entering(size);
     std::cout << size << "th fibo = " << recFibo(size - 1) << std::endl;
     entering(size);
     std::cout << size << "th fibo = " << recFibo(size - 1) << std::endl;
     entering(size);
     std::cout << size << "th fibo = " << fibo(size) << std::endl;
     entering(size);
     std::cout << size << "th fibo = " << fibo(size) << std::endl;
     return 0;
 }