Test Project: recFibo
recFibo()
int recFibo (int n)
recursive calculate fibonacci number
Parameters
n - n-th number fibonacci
Returns
return n-th number of fibonacci
Definition at line 39 of file fibonachi.cpp.
References recFibo(), and vec.
Referenced by main(), and recFibo().
                    {
     if(n < vec.size()) {
         return vec[n];
     } else {
         int tmp = recFibo(n-1) + recFibo(n-2);
         vec.push_back(tmp);
         return tmp;
     }
 }