Test Project: Fibonacci/fibonachi.h File Reference
fibonachi.h File Reference
Functions
void entering (int &size)
entering size and check size greather 0
int recFibo (int n)
recursive calculate fibonacci number
Function Documentation
entering()
void entering (int & size)
entering size and check size greather 0
Parameters
size - size get by reference for fix changes
Definition at line 29 of file fibonachi.cpp.
Referenced by main().
{
     std::cout << "enter size: ";
     std::cin >> size;
     while (size < 1) {
         std::cout << "Enter number greather 0: ";
         std::cin >> size;
     }
 }
recFibo()
int recFibo (int n)
recursive calculate fibonacci number
Parameters
n - n-th number fibonacci
Returns
return n-th number of fibonacci
Definition at line 39 of file fibonachi.cpp.
References recFibo(), and vec.
Referenced by main(), and recFibo().
                    {
     if(n < vec.size()) {
         return vec[n];
     } else {
         int tmp = recFibo(n-1) + recFibo(n-2);
         vec.push_back(tmp);
         return tmp;
     }
 }