Test Project: Fibonacci/fibonachi.cpp File Reference
fibonachi.cpp File Reference
#include <iostream>
#include <vector>
Functions
void entering (int &)
entering size and check size greather 0
int recFibo (int)
recursive calculate fibonacci number
int fibo (int)
int main ()
Variables
std::vector< int > vec = {0, 1}
Function Documentation
entering()
void entering (int & size)
entering size and check size greather 0
Parameters
size - size get by reference for fix changes
Definition at line 29 of file fibonachi.cpp.
Referenced by main().
{
     std::cout << "enter size: ";
     std::cin >> size;
     while (size < 1) {
         std::cout << "Enter number greather 0: ";
         std::cin >> size;
     }
 }
fibo()
int fibo (int size)
Definition at line 50 of file fibonachi.cpp.
References vec.
Referenced by main().
                    {
     if(vec.size() == 0) {
         for(int i = 0; i < size; ++i) {
             if(i == 0 || i == 1) {
                 vec.push_back(i);
             } else {
                 vec.push_back(vec[i - 1] + vec[i - 2]);
             }
         }
     } else if(size > vec.size()) {
         if(vec.size() == 1) {
             vec.push_back(1);
         }
         for(int i = vec.size(); i < size; ++i) {
             vec.push_back(vec[i - 1] + vec[i - 2]);
         }
     }
     return vec[size - 1];
 }
main()
int main ()
Definition at line 10 of file fibonachi.cpp.
References entering(), fibo(), and recFibo().
            {
     int size;
     entering(size);
     std::cout << size << "th fibo = " << recFibo(size - 1) << std::endl;
     entering(size);
     std::cout << size << "th fibo = " << recFibo(size - 1) << std::endl;
     entering(size);
     std::cout << size << "th fibo = " << fibo(size) << std::endl;
     entering(size);
     std::cout << size << "th fibo = " << fibo(size) << std::endl;
     return 0;
 }
recFibo()
int recFibo (int n)
recursive calculate fibonacci number
Parameters
n - n-th number fibonacci
Returns
return n-th number of fibonacci
Definition at line 39 of file fibonachi.cpp.
References recFibo(), and vec.
Referenced by main(), and recFibo().
                    {
     if(n < vec.size()) {
         return vec[n];
     } else {
         int tmp = recFibo(n-1) + recFibo(n-2);
         vec.push_back(tmp);
         return tmp;
     }
 }
Variable Documentation
vec
std::vector<int> vec = {0, 1}
Definition at line 5 of file fibonachi.cpp.
Referenced by fibo(), and recFibo().