Test Project: main
main()
int main ()
Definition at line 244 of file vector.cpp.
References Vector< T >::begin(), Vector< T >::capacity(), Vector< T >::empty(), Vector< T >::end(), Vector< T >::pop_back(), Vector< T >::push_back(), Vector< T >::rbegin(), Vector< T >::rend(), Vector< T >::reserve(), Vector< T >::resize(), Vector< T >::shrink_to_fit(), and Vector< T >::size().
            {
     Vector<int> obj(2, 7);
     obj.push_back(5);
     obj.push_back(4);
     obj.push_back(5);
     obj.push_back(65);
     int count = 0;
     //print vector items from begin to end
     std::cout << "vector from begin to end"<< obj.capacity() << std::endl;
     for(Vector<int>::Iterator i = obj.begin(); i != obj.end(); ++i) {
         std::cout << "vector[" << count++ << "] = " << *(i) << std::endl;
     }
     obj.pop_back();
     obj.pop_back();
     count -= 2;
     //print vector items from end to begin
     std::cout << std::endl << "vector from end to begin" << std::endl;
     for(Vector<int>::Iterator i = obj.rbegin(); i != obj.rend(); --i) {
         std::cout << "vector[" << --count << "] = " << *(i) << std::endl;
     }
     if(obj.empty()) {
         std::cout << "vector  is empty" << std::endl;
     } else {
         std::cout << "vector is'n empty" << std::endl;
     }
     std::cout << "size1:  " << obj.size() << std::endl;
     std::cout << "capacity1:  " << obj.capacity() << std::endl;
     obj.resize(3, 88);
     std::cout << "resize size:  " << obj.size() << std::endl;
     std::cout << "resize capacity:  " << obj.capacity() << std::endl;
     for(int i = 0 ; i < obj.size(); ++i){
         std::cout << " vec: " << obj[i] <<std::endl;
     }
     obj.reserve(15);
     std::cout << "reserve size:  " << obj.size() << std::endl;
     std::cout << "reserve capacity:  " << obj.capacity() << std::endl;
     obj.shrink_to_fit();
     std::cout << "size:  " << obj.size() << std::endl;
     std::cout << "capacity:  " << obj.capacity() << std::endl;
     return 0;
 }